version: 2.1

orbs:
  semver: tmo-orb/semver@1.5.1

# jobs:
#   publish-github-release:
#     docker:
#       - image: cibuilds/github:0.10
#     steps:
#       - checkout
#       - run:
#           name: "Adding environment variables for tests"
#           command: |
#             echo "export config_path='/home/circleci/.utils.config'" >> "$BASH_ENV"
#             mkdir -p /home/circleci/
#             touch /home/circleci/.utils.config

#       - run: 
#           name: "Archive app"
#           command: | 
#             zip -r asf.zip README.md
#       - run:
#           name: "Install python"
#           command: apk add --no-cache python3

#       - run:
#           name: "Load release_tag parameters to env"
#           command: |
#             echo "answer=OLD_TAG" > $config_path
#       - semver/release_tag

#       - run:
#           name: "Load commit_message parameters to env"
#           command: |
#             echo "answer=MSG" > $config_path
#       - semver/commit_message

#       - run: 
#           name: "something"
#           command: |
#             echo $OLD_TAG
#             echo $MSG

#       - run:
#           name: "Load parameters to env"
#           command: |
#             echo "text=\"${MSG}\"" > $config_path
#             echo "flag=r" >> $config_path
#             echo "answer=RELEASE_LEVEL" >> $config_path
#       - semver/flag-value

#       - run: 
#           name: "something"
#           command: |
#             echo $RELEASE_LEVEL

#       - run:
#           name: "Load parameters to env"
#           command: |
#             echo "version=\"${OLD_TAG}\"" > $config_path
#             echo "option=\"${RELEASE_LEVEL}\"" >> $config_path
#             echo "answer=NEW_TAG" >> $config_path
#       - semver/semver-increment

#       - run: 
#           name: "something"
#           command: |
#             echo $NEW_TAG

#       - run:
#           name: "Publish Release on GitHub"
#           command: | 
#             ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${NEW_TAG} ./asf.zip

workflows:
  main:
    jobs:
      - semver/update_semver:
          assets_path: "./asf.zip"
          create_asset:
              - run:
                  name: "Create ZIP"
                  command: "zip -r asf.zip README.md"
          filters:
            branches:
              only:
                - master
            # tags:
            #   only: /^v+\d+\.\d+\.\d+$/
