version: 2.1

jobs:
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - checkout
      - run: 
          name: "Tag value"
          command: | 
              version=`curl https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/releases/latest -s | jq .name -r` &&
              # version=`echo $version | awk 'BEGIN { FS = "." } ; { print $1 "\." $2 "\." $3 + 1 }'` &&
              # echo $version &&
              git clone https://gist.github.com/c227d9c65b09d2be2d99abbfcfa8774a.git SemVer &&
              chmod 777 SemVer/increment_version 
              version=`./SemVer/increment_version -p $version`
              echo "export VERSION=${version}" >> "$BASH_ENV"
      - run: 
          name: "Archive app"
          command: | 
            zip -r asf.zip README.md
      - run:
          name: "Publish Release on GitHub"
          command: | 
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./asf.zip

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  main:
    jobs:
      - publish-github-release:
          filters:
            # branches:
            #   only:
            #     - master
            tags:
              only: /^\d+\.\d+\.\d+$/

commands: # a reusable command with parameters
  version-update:
    parameters:
      level:
        default: 0
        type: integer
    steps:
      - run: echo "Hello <<parameters.to>>"
