version: 2.1

orbs:
  semver: tmo-orb/semver@1.1.0

jobs:
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - checkout
      # - when:
      #     condition:
      #         not: << pipeline.git.tag >>
      #     steps:
      #       - set-new-version-tag
      # - when:
      #     condition: << pipeline.git.tag >>
      #     steps:
      #       - run: 
      #           name: "SemVer version update"
      #           command: echo "export VERSION=<< pipeline.git.tag >>" >> "$BASH_ENV"
      - run: 
          name: "Archive app"
          command: | 
            zip -r asf.zip README.md
      - run:
          name: "Install python"
          command: apk add --no-cache python3
      # - run:
      #     name: "Publish Release on GitHub"
      #     command: | 
      #       ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_USERNAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./asf.zip
      - run:
          name: "Get current tag"
          command: |
            version=`curl https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/releases/latest -s | jq .name -r` &&
            echo "export OLD_VERSION=${version}" >> "$BASH_ENV"
            echo $OLD_VERSION
      - run:
          name: "Get PR title"
          command: |
            title=$(git log --format=oneline -n 1 $CIRCLE_SHA1)
            echo "export TITLE=\"${title}\"" >> "$BASH_ENV"
            echo git log --format=oneline -n 1 $CIRCLE_SHA1
            echo $title
            echo $TITLE
      - semver/flag-value:
          text: $TITLE
          flag: "r"
          answer: "FLAG"
      - semver/semver-increment:
          level: $FLAG
          version: "v0.0.1"
      - run:
          name: "Publish Release on GitHub"
          command: | 
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_USERNAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./asf.zip

workflows:
  main:
    jobs:
      - publish-github-release:
          filters:
            branches:
              only:
                - master
            # tags:
            #   only: /^v+\d+\.\d+\.\d+$/

commands: # a reusable command with parameters
  set-new-version-tag:
    description: "Get Semver tag from github via git API, update it via script and set into BASH_ENV"
    parameters:
      level:
        description: "Which semver level will be incremented [M/m/p] for Major/minor/patch"
        default: "p"
        type: string
    steps:
      - run:
          name: "SemVer version update increment"
          command: |
            version=`curl https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/releases/latest -s | jq .name -r` &&
            git clone https://gist.github.com/GagMirz/750dc7cffbc6cd37750cb07ed5a616d5 SemVer &&
            chmod 777 SemVer/increment_version.sh 
            version=`./SemVer/increment_version.sh -<<parameters.level>> $version`
            echo "export VERSION=${version}" >> "$BASH_ENV"

