version: 2.1

jobs:
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - checkout
      - when:
          condition: << pipeline.git.tag >>
          steps:
            - version-tag-update
      - when:
          condition:
              not: << pipeline.git.tag >>
          steps:
            - run: 
                name: "SemVer version update"
                command: echo "export VERSION=<< pipeline.git.tag >>" >> "$BASH_ENV"
      - run: 
          name: "Archive app"
          command: | 
            zip -r asf.zip README.md
      - run:
          name: "Publish Release on GitHub"
          command: | 
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./asf.zip

workflows:
  main:
    jobs:
      - publish-github-release:
          filters:
            branches:
              only:
                - master
            tags:
              only: /^v+\d+\.\d+\.\d+$/

commands: # a reusable command with parameters
  version-tag-update:
    parameters:
      level:
        default: "p"
        type: string
    steps:
      - run:
          name: "SemVer version update increment"
          command: |
            version=`curl https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/releases/latest -s | jq .name -r` &&
            git clone https://gist.github.com/GagMirz/750dc7cffbc6cd37750cb07ed5a616d5 SemVer &&
            chmod 777 SemVer/increment_version.sh 
            version=`./SemVer/increment_version.sh -<<parameters.level>> $version`
            echo "export VERSION=${version}" >> "$BASH_ENV"

